version: '3.8'

services:
  "2048":
    container_name: 2048-game
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      # Montar archivos (ahora funcionar√° porque ya existen en el contenedor)
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./nginx.conf:/etc/nginx/conf.d/default. conf:ro
    restart: unless-stopped
    networks:
      - 2048-network

networks:
  2048-network:
    driver: bridge